openapi: 3.0.0
x-stoplight:
  id: dy38btjk9ql0c
info:
  title: aha
  version: '1.0'
  contact:
    name: Reynanda Putra Pratama
    url: 'https://reynandaptr.dev/'
    email: reynandapp1997@gmail.com
  description: AHA
servers:
  - url: 'https://aha-api.reynandaptr.dev/v1'
    description: Production
tags:
  - name: Authentication
    description: Authentication endpoint
  - name: Analytics
    description: Analytics endpoint
paths:
  /auth/login:
    post:
      summary: ''
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      tags:
        - Authentication
  /auth/sign-up:
    parameters: []
    post:
      summary: ''
      operationId: post-auth-sign-up
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequestBody'
      tags:
        - Authentication
  /auth/validate-token:
    get:
      summary: ''
      operationId: get-auth-validate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/ValidateResponseBody'
      security:
        - aha_jwt: []
      tags:
        - Authentication
    parameters: []
  /auth/email-verification:
    post:
      summary: ''
      operationId: post-auth-email-verification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      parameters: []
      tags:
        - Authentication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailVerificationRequestBody'
  /auth/resend-email-verification:
    post:
      summary: ''
      operationId: post-auth-resend-email-verification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      security:
        - aha_jwt: []
      tags:
        - Authentication
  /auth/reset-password:
    post:
      summary: ''
      operationId: post-auth-reset-password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseBody'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequestBody'
      security:
        - aha_jwt: []
      tags:
        - Authentication
  /auth/logout:
    post:
      summary: ''
      operationId: post-auth-logout
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseBody'
      tags:
        - Authentication
  /auth/profile:
    put:
      summary: ''
      operationId: put-auth-profile
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      security:
        - aha_jwt: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfileRequestBody'
      tags:
        - Authentication
  /auth/login/google:
    get:
      summary: ''
      operationId: get-auth-login-google
      responses:
        '302':
          description: Found
      tags:
        - Authentication
  /auth/redirect/google:
    get:
      summary: ''
      operationId: get-auth-redirect-google
      responses:
        '302':
          description: Found
      tags:
        - Authentication
      parameters:
        - schema:
            type: string
          in: query
          name: code
  /analytics/users:
    get:
      summary: ''
      operationId: get-analytics-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/UserAnalyticsResponse'
      x-extension-1: null
      tags:
        - Analytics
  /analytics/users/online:
    parameters: []
    get:
      summary: ''
      operationId: get-analytics-users-online
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/UserOnlineAnalyticsResponseBody'
      tags:
        - Analytics
components:
  schemas:
    BaseResponseBody:
      title: BaseResponseBody
      x-stoplight:
        id: gyzkbtjex84v0
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        error:
          type: string
    LoginRequestBody:
      title: LoginRequestBody
      x-stoplight:
        id: 2v0vvrjfx436r
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    SignUpRequestBody:
      title: SignUpRequestBody
      x-stoplight:
        id: 4yyfxjyekl4lz
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        repassword:
          type: string
      required:
        - email
        - password
        - repassword
    ValidateResponseBody:
      title: ValidateResponseBody
      x-stoplight:
        id: opvmi4cgq6mzc
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        is_verified:
          type: boolean
        provider:
          type: string
    ResetPasswordRequestBody:
      title: ResetPasswordRequestBody
      x-stoplight:
        id: 5mln5u4ulo6y6
      type: object
      properties:
        old_password:
          type: string
        new_password:
          type: string
        renew_password:
          type: string
    EmailVerificationRequestBody:
      title: EmailVerificationRequestBody
      x-stoplight:
        id: iiupvjlbgdrk7
      type: object
      properties:
        session_id:
          type: string
        session_token:
          type: string
    UpdateUserProfileRequestBody:
      title: UpdateUserProfileRequestBody
      x-stoplight:
        id: 1p58lh70qo1kn
      type: object
      properties:
        name:
          type: string
    UserAnalyticsResponse:
      title: AnalyticsUsersResponseBody
      x-stoplight:
        id: fcaafa1516c36
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        is_verified:
          type: boolean
        provider:
          type: string
        login_count:
          type: integer
        signup_timestamp:
          type: string
        last_session_timestamp:
          type: string
    UserOnlineAnalyticsResponseBody:
      title: UserOnlineAnalyticsResponseBody
      x-stoplight:
        id: d0wiyv35x8xti
      type: object
      properties:
        user_count:
          type: integer
        user_active_session_count:
          type: integer
        average_active_user:
          type: integer
  securitySchemes:
    aha_jwt:
      name: aha_jwt
      type: apiKey
      in: cookie
