openapi: 3.0.0
x-stoplight:
  id: dy38btjk9ql0c
info:
  title: aha
  version: '1.0'
  contact:
    name: Reynanda Putra Pratama
    url: 'https://reynandaptr.dev/'
    email: reynandapp1997@gmail.com
  description: AHA
servers:
  - url: 'https://aha-core-production.up.railway.app/v1'
    description: Production
tags:
  - name: Authentication
    description: Authentication endpoint
paths:
  /auth/login:
    post:
      summary: ''
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
      tags:
        - Authentication
  /auth/sign-up:
    parameters: []
    post:
      summary: ''
      operationId: post-auth-sign-up
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequestBody'
      tags:
        - Authentication
  /auth/validate-token:
    get:
      summary: ''
      operationId: get-auth-validate
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
                  - type: object
                    properties:
                      data:
                        $ref: '#/components/schemas/ValidateResponseBody'
      security:
        - aha_jwt: []
      tags:
        - Authentication
    parameters: []
  /auth/email-verification:
    post:
      summary: ''
      operationId: post-auth-email-verification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      parameters:
        - schema:
            type: string
          in: header
          name: session_id
        - schema:
            type: string
          in: header
          name: session_token
      security:
        - aha_jwt: []
  /auth/resend-email-verification:
    post:
      summary: ''
      operationId: post-auth-resend-email-verification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResponseBody'
      security:
        - aha_jwt: []
  /auth/reset-password:
    post:
      summary: ''
      operationId: post-auth-reset-password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseBody'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequestBody'
      security:
        - aha_jwt: []
  /auth/logout:
    post:
      summary: ''
      operationId: post-auth-logout
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponseBody'
components:
  schemas:
    BaseResponseBody:
      title: BaseResponseBody
      x-stoplight:
        id: gyzkbtjex84v0
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        error:
          type: string
    LoginRequestBody:
      title: LoginRequestBody
      x-stoplight:
        id: 2v0vvrjfx436r
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    SignUpRequestBody:
      title: SignUpRequestBody
      x-stoplight:
        id: 4yyfxjyekl4lz
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        repassword:
          type: string
      required:
        - email
        - password
        - repassword
    ValidateResponseBody:
      title: ValidateResponseBody
      x-stoplight:
        id: opvmi4cgq6mzc
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        is_verified:
          type: boolean
        provider:
          type: string
    ResetPasswordRequestBody:
      title: ResetPasswordRequestBody
      x-stoplight:
        id: 5mln5u4ulo6y6
      type: object
      properties:
        old_password:
          type: string
        new_password:
          type: string
        renew_password:
          type: string
  securitySchemes:
    aha_jwt:
      name: aha_jwt
      type: apiKey
      in: cookie
